modLoader="javafml" #mandatory
loaderVersion="[34,)"
license="MIT"
issueTrackerURL="https://github.com/wonderbird/minecraft-forge-hello-world" #optional

[[mods]]
modId="sboosmodhello"
version="0.0.1"
displayName="SBoos Mod Hello" #mandatory
updateJSONURL="https://raw.githubusercontent.com/wonderbird/minecraft-forge-hello-world/main/update.json"
displayURL="https://github.com/wonderbird/minecraft-forge-hello-world"
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to the Forge authors"
authors="SBoos" #optional
description='''
This mod just shows Hello World :-)

Have fun!
'''

[[dependencies.sboosmodhello]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sboosmodhello]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
